# Language: Portuguese (Brazil)
# Com fileira Esc/Tab/Ctrl/Alt/Shift/setas (keyboard-config)
---
outlines:
    default:     { width: 53.76,  height: 42 }
    small-row: { width: 59.733, height: 25.2 }
    change-view: { width: 80.64,  height: 42 }
    large:       { width: 80.64,  height: 42 }
    spaceline:   { width: 147.84, height: 42 }
    special:     { width: 53.76,  height: 42 }
    special-2:   { width: 80.64,  height: 42 }
    special-3:   { width: 94.08,  height: 42 }
    thin:        { width: 40.32,  height: 42 }

views:
    base:
        - "Esc-small Tab-small Ctrl Alt Shift ↑ ↓ ← →"
        - "q w e r t y u i o p"
        - "a s d f g h j k l ç"
        - "show_upper z x c v b n m BackSpace"
        - "show_numbers show_eschars preferences space .-large Return"
    upper:
        - "Esc-small Tab-small Ctrl Alt Shift ↑ ↓ ← →"
        - "Q W E R T Y U I O P"
        - "A S D F G H J K L Ç"
        - "show_upper Z X C V B N M BackSpace"
        - "show_numbers show_eschars preferences space ,-large Return"
    numbers:
        - "Esc-small Tab-small Ctrl Alt Shift ↑ ↓ ← →"
        - "1 2 3 4 5 6 7 8 9 0"
        - "@ # $ % & - _ + ( )"
        - "show_symbols , \" ' : ; ! ? BackSpace"
        - "show_letters show_eschars preferences space º .-thin Return"
    symbols:
        - "Esc-small Tab-small Ctrl Alt Shift ↑ ↓ ← →"
        - "~ ` | · √ π τ ÷ × ¶"
        - "© ® £ € ¥ ^ ° * { }"
        - "show_numbers \\ / < > = [ ] BackSpace"
        - "show_letters show_eschars preferences space ≠ § Return"
    eschars:
        - "Esc-small Tab-small Ctrl Alt Shift ↑ ↓ ← →"
        - "À Á Ã Â É Ê Í Ó Ô Õ"
        - "à á ã â é ê í ó ô õ "
        - "show_numbers Ú Ü ú ü ! ? . BackSpace"
        - "show_letters show_eschars preferences space « » Return"

buttons:
    show_upper:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "change-view"
        icon: "key-shift"
    BackSpace:
        outline: "special-2"
        icon: "edit-clear-symbolic"
        action: "erase"
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "change-view"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "change-view"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "change-view"
        label: "*/="
    show_eschars:
        action:
            locking:
                lock_view: "eschars"
                unlock_view: "base"
        outline: "change-view"
        label: "Ãã"
    .-large:
        outline: "large"
        text: "."
    ",-large":
        outline: "large"
        text: ","
    space:
        outline: "spaceline"
        text: " "
    Return:
        outline: "special-3"
        icon: "key-enter"
        keysym: "Return"
    «:
        outline: "thin"
    »:
        outline: "thin"
    º:
        outline: "thin"
    .-thin:
        outline: "thin"
        text: "."
    ≠:
        outline: "thin"
    §:
        outline: "thin"
    Esc-small:
        outline: "small-row"
        keysym: "Escape"
        label: "Esc"
    Tab-small:
        outline: "small-row"
        keysym: "Tab"
        label: "Tab"
    Ctrl:
        modifier: "Control"
        outline: "small-row"
        label: "Ctrl"
    Alt:
        modifier: "Alt"
        outline: "small-row"
        label: "Alt"
    Shift:
        modifier: "Shift"
        outline: "small-row"
        label: "Shift"
    "↑":
        outline: "small-row"
        keysym: "Up"
    "↓":
        outline: "small-row"
        keysym: "Down"
    "←":
        outline: "small-row"
        keysym: "Left"
    "→":
        outline: "small-row"
        keysym: "Right"
